name: rust_web_app_workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: target
        key: crate-${{ hashFiles('Cargo.toml') }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --no-default-features --verbose
