name: rust_web_app_workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build_cache:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: ./.github/actions/cache_cargo

      - name: Build
        run: cargo build --verbose
        working-directory: app

  fmt:
    runs-on: ubuntu-latest

    needs: build_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rustfmt
        run: rustup component add rustfmt

      - name: Restore cache
        uses: ./.github/actions/cache_cargo

      - name: Exec rustfmt
        run: cargo fmt --all -- --check
        working-directory: app

  clippy:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    needs: build_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rustfmt
        run: rustup component add clippy

      - name: Restore cache
        uses: ./.github/actions/cache_cargo

      - name: Exec clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
        working-directory: app

  test:
    runs-on: ubuntu-latest

    env:
      RUSTC_FORCE_INCREMENTAL: 1

    needs: build_cache

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore cache
        uses: ./.github/actions/cache_cargo

      - name: Run tests
        run: cargo test --no-default-features
        working-directory: app
